CACHE_CONNECTION_PREFIX = 'u'

MAIN_GROUP_NAME = 'group'

ACTION_AUTH_LOGIN = 'AUTH_LOGIN'

ACTION_MESSAGE = 'MESSAGE'
ACTION_MESSAGE_ERROR = 'MESSAGE_ERROR'

ACTION_TIMESTAMP = 'ACTION_TIMESTAMP'

ACTION_HELLO = 'HELLO'

ACTION_CONNECTED = 'CONNECTED'

ACTION_CONNECTS = 'CONNECTS'
ACTION_DISCONNECTS = 'DISCONNECTS'
